BoxingAgent:
    trainer: ppo
    batch_size: 1024
    buffer_size: 20480
    learning_rate: 1.0e-4
    beta: 0.01
    epsilon: 0.2
    lambd: 0.95
    num_epoch: 3
    learning_rate_schedule: linear
    normalize: false
    hidden_units: 32
    num_layers: 2
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            gamma: 0.8
            strength: 1.0
    keep_checkpoints: 100
    checkpoint_interval: 200000
    max_steps: 5000000
    memory_size: 256
    time_horizon: 128
    sequence_length: 128
    summary_freq: 100000
    use_recurrent: false
    threaded: true
env_settings:
    env_path: ./Builds/MetaBoxing
    num_envs: 4
engine_settings:
    time_scale: 1
    no_graphics: true
